accounts/urls.py
from django.urls import path 

from .views import(
    user_create_view,
    user_login_view,
    user_logout_view,
    user_profile_view
)
# app name
app_name = 'accounts'

urlpatterns = [
    path('create/', user_create_view, name = "create"),
    path('login/', user_login_view, name = "login"),
    path('logout/', user_logout_view, name = "logout"),
    path('<str:username>/', user_profile_view, name = "profile")
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('static_pages.urls', namespace='static_pages')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]

posts/urls.py
from django.urls import path

# import all views of the archive views.py
from .views import (
    post_create_view,
    post_detail_view,
    post_list_view,
    post_update_view,
    post_delete_view
)

# App name
app_name = 'posts'

# urls 
urlpatterns = [
    path('create/', post_create_view, name='create'),
    path('detail/<int:id>', post_detail_view, name='detail'),
    path('list/', post_list_view, name='list'),
    path('update/<int:id>', post_update_view, name='update'),
    path('delete/<int:id>', post_delete_view, name='delete')
]

static_pages/urls.py
from django.urls import path

from .views import home_view # home_view is the funcion that return to the archive html 

app_name = 'static_pages'

# Note: the path is the route of the web
urlpatterns = [
    path('home', home_view, name='home'),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

User = settings.AUTH_USER_MODEL

class Post(models.Model):
    title = models.CharField(max_length = 255, blank = True, null = True)
    content = models.TextField(blank = True, null = True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete = models.CASCADE, blank = True, null = True)
    

static_pages/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, authenticate, login, logout

from posts.models import Post

# view for create the user
User = get_user_model()

def user_create_view(request):
    if request.method == "POST":
        context = {}
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if password1 == password2:
           # Create user
           username = request.POST['username']
           email = request.POST['email']

        # Check if the user already exists
           try:
                # if the user already exists, finds the user and email in the database 
               user1 = User.objects.get(username = username)
               context['error'] = "Username or email is already in the system!"
               return render(request, 'accounts/create.html', context = context)
           except User.DoesNotExist:
                try:
                  user2 = User.objects.get(email = email)
                   # sends a message
                  context['error'] = "Username or email is already in system!"
                  return render(request, 'accounts/create.html', context = context) 
        # If the user not exist in database 
                except User.DoesNotExist:
                    # Create the user
                        user = User.objects.create_user(username = username, email = email, password = password1)
                        return redirect('posts:list')      
        else:
            context['error'] = "Passwords must match!"
            return render(request, 'accounts/create.html', context = context)
    else:
        return render(request, 'accounts/create.html')

# view for user login
def user_login_view(request):
    if request.method == "POST":
         context = {}
         username = request.POST['username']
         password = request.POST['password']
         user = authenticate(username = username, password = password)
        # check if the user exists in database
         if user is not None:
             login(request, user) # login the user
             context['success'] = "You are logged in!" # send a message 
             return render(request, 'accounts/login.html', context)
        # if the user not exist in database
         else:
            context['error'] = "Invalid Login"
            return render(request, 'accounts/login.html', context)
    else:   
        return render(request, 'accounts/login.html')

# view for logout 
def user_logout_view(request):
    if request.user.is_authenticated:
        # log out user
        logout(request)
        return render(request, 'accounts/logout.html')
    else:
        return redirect('accounts:login')

# view for user profile 
def user_profile_view(request, username):
    user = User.objects.get(username=username)
    posts = Post.objects.filter(author = user)
    context = {'posts':posts}
    return render(request, 'accounts/profile.html', context = context)

posts/views.py
from django.http import request
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

from .models import Post

# this is our create post view
@login_required
def post_create_view(request):
    if request.method == "POST":
        context = {}
        title = request.POST['title']
        content = request.POST['content']

        if title and content:
            # if create form is valid 
             user = request.user
             post = Post.objects.create(title = title, content = content, author = user)
             return redirect('posts:detail', id = post.id)
        else:
             context['error'] = "Your title and content can't be empty"
             return render(request, 'posts/create.html', context = context)

    else:
        return render(request, 'posts/create.html')



# this is to view one specific blog post
def post_detail_view(request, id):
    post = Post.objects.filter(id = id).first()
    context = {'post': post}
    return render(request, 'posts/detail.html', context = context)

# this will be to view all of our blog posts
def post_list_view(request):
    posts = Post.objects.all()
    context = {'posts': posts}
    return render(request, 'posts/list.html', context = context)


# this will be to update one specific post
@login_required
def post_update_view(request, id):
    context = {}
    post = Post.objects.filter(id = id).first()
    context['post'] = post
    if request.user == post.author:
     
        if request.method == "POST":
            title = request.POST['title']
            content = request.POST['content']

            if title and content:
                # if update form is valid 
                post.title = title
                post.content = context
                post.save() 
                context['success'] = "Updated"
                return render(request, 'posts/update.html', context = context)
            else:
                context['error'] = "Your title and content can't be empty"
                return render(request, 'posts/update.html', context = context)
        else:
            return render(request, 'posts/update.html', context = context)
        
    else:
        return redirect('posts:list')


# this will be to delete one specific post
@login_required
def post_delete_view(request, id):
    post = Post.objects.filter(id=id).first()
    if request.user == post.author:
        if request.method == "POST":
            post.delete()
            return redirect('posts:list')
        else:   
            return render(request, 'posts/delete.html')
    else:
        return redirect('posts:list')

static_pages/views.py
from django.shortcuts import render

# Create your views here.

#
def home_view(request):
    return render(request, 'static_pages/home.html')

accounts/templates/accounts/create.html
<!-- for use the code of myblog/templates/base.html/ in this file-->
{% extends 'base.html' %}
{% block content%}

<div class="container">
    <div class="row">
        <div class="col-12">
            <h1 class = "display-4">Sign Up</h1>
            <h4 class="text-danger">{{error}}</h4>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-12">
            <form method = "POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type = "text" class = "form-control" name = "username" required>
                </div>
                <div class="form-group">
                    <label for="email">E-mail</label>
                    <input type = "email" class = "form-control" name = "email" required>
                </div>
                <div class="form-group">
                    <label for="password1">Password</label>
                    <input type = "password" class = "form-control" name = "password1" required>
                </div>
                <div class="form-group">
                    <label for="password2">Confirm Password</label>
                    <input type = "password" class = "form-control" name = "password2" required>
                </div>
                <br>
                <input type = "submit" value="Sign Up" class = "btn btn-md btn-primary">
            </form>
        </div>
    </div>
</div>

{% endblock content%}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class = "row">
        <div class = "col-12">
            <h1 class = "display-4">Log in</h1>
            {% if success %}
                <h4 class = "text-success">{{success}}</h4>
            {% else %}
                <h4 class="text-danger">{{error}}</h4>
            {% endif %}
        </div>
    </div>
    <div class = "row">
        <div class="col-12">
        <form method = "POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name = "username" class="form-control">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name = "password" class = "form-control">
            </div>
            <br>
            <input type = "submit" value = "Log In" class="btn btn-md btn-primary">
        </form>
      </div>
    </div>
</div>

{% endblock content %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <h1 class="display-4">You are now logget ou!t</h1>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <h1 class = "display-4">{{user}}'s Blog</h1>
    </div>
    <br>
<div class="row">
    <div class="col-12">
         {% for p in posts %}
            <div class="row">
                <div class="col-12">
                <a href = "{% url 'posts:detail' id=p.id %}">{{p.title}}</a>
                <br>
                <p>{{p.content|slice:"255"}}</p>
                </div>
            </div>
            <hr>
         {% endfor %}
     </div>
    </div>   
</div>  
{% endblock content %}

myblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Django Blog</title>
    <!-- CSS Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock content%}
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


</body>
</html>

myblog/templates/navbar.html
<!-- Nav Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'static_pages:home' %}">Django Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href = "{% url 'posts:list' %}">All Blog Posts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'posts:create' %}">Create a Blog</a>
              </li>
              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>

              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:create' %}">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
              </li>

              {% endif %}
          </ul>
        </div>
      </nav>

posts/templates/posts/create.html
<!-- for use the code of myblog/templates/base.html/ in this file-->
{% extends 'base.html' %}
{% block content %}
    <div class="container px-5">

     <div class="row">
            <h1 class="display-4">Create a New Post</h1>   
    </div>

    <!-- Error message -->
    <div class="row">
        <h4 class = "text-danger">{{error}}</h4>
    </div>

    <div class="row">
        <div class="col-12">
        <!-- formulary to create a new post -->
            <form method="POST">
                {% csrf_token %}

                <div class="form-group">
                    <label for="title">Post Title</label>
                    <input type="text" name = "title" class="form-control" required/>
                </div>
                <div class="form-group">
                    <label for="content">Post content</label>
                    <textarea name="content" id="" cols="30" rows="10" class="form-control"></textarea>

                </div>
                <br>
                        <!-- Create botom-->
                    <input type="submit" value="Create" class="btn btn-md btn-primary mr-2"/>
                        <!-- Cancel botom-->
                    <a href="{% url 'posts:list' %}" class="btn btn-md btn-danger">cancel</a>
            </form>
           
          </div>
        </div>
    </div>
{% endblock content %}

posts/templates/posts/delete.html
<!-- for use the code of myblog/templates/base.html/ in this file-->
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1 class = "text-danger">{{error}}</h1>
            <h1 class="display-4">Are you sure you want to delete?</h1>
        </div>
    </div>
    <div class="row">
        <!-- Form for delete a especific post -->
        <div class="col-12">
            <form method = "POST">
                {% csrf_token %}
                <input type = "submit" value= "Yes" class = "btn btn-md btn-danger"/>
                <a href = "{% url 'posts:list' %}" class = "btn btn-md btn-primary">No</a>
            </form>
        </div>
    </div>
</div>
   
{% endblock content %}

posts/templates/posts/detail.html
<!-- for use the code of myblog/templates/base.html/ in this file-->
{% extends 'base.html' %}
{% block content %}

    <div class = "container">
        <div class = "row">
            <div class="col-12">
            <h1 class="display-4">{{post.title}}</h1>
            <br />
                <p>
                    Written by: {{post.author}}
                </p>
                <p>Created: {{post.created}} | Updated: {{post.updated}}</p>
                
        </div>
    </div>
        <div class="row">
            <div class="col-12">
                <p>
                    {{post.content}}
                </p>
            </div>
            
        </div>
       
    {% if request.user == post.author %}
    <div class="row">
        <div class="col-12">
                <a href = "{% url 'posts:update' id=post.id %}" class="btn btn-md btn-secondary">Edit</a>
                <a href = "{% url 'posts:delete' id=post.id %}" class="btn btn-md btn-danger">Delete</a>
        </div>
    </div>
    {% endif %}
    </div>    
</div> 
<br>

{% endblock content %}

posts/templates/posts/list.html
<!-- for use the code of myblog/templates/base.html/ in this file-->
{% extends 'base.html' %}
{% block content %}
<div class="container px-5">
    <div class="row">
        <h1 class="display-4">The Blog</h1>
        
    </div>
    <div class="row">
        <div class="col-12">
             {% for p in posts %}
                <div class="row">
                    <div class="col-12">
                    <a href = "{% url 'posts:detail' id=p.id %}">{{p.title}}</a>
                    <br>
                    <p>{{p.content|slice:"255"}}</p>
                    </div>
                </div>
                <hr>
             {% endfor %}
        </div>
    </div>     
</div>

{% endblock content %}

posts/templates/posts/update.html
<!-- for use the code of myblog/templates/base.html/ in this file-->
{% extends 'base.html' %}
{% block content %}
<div class = "container px-5">
    <div class="row">
        <div class="col-12">
            <h1 class="display-4">Update Post</h1>
            <h4 class="text-danger">{{error}}</h4>
            <h4 class="text-success">{{success}}</h4>
        </div>
    </div>
    <br>

     <!-- formulary to update a especific post -->
    <div class="row">
        <div class="col-12">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">Post Title</label>
                    <input type="text" name = "title" value = "{{post.title}}" class="form-control"/>
                </div>
                <br>
                <div class="form-group">
                    <label for="content">Post Content</label>
                    <textarea name="content" rows="8" class="form-control">{{post.content}}</textarea>
                </div>
                <br>
                <input type="submit" value="Update" class = "btn btn-md btn-primary"/>
                <a href = "{% url 'posts:detail' id=post.id %}" class = "btn btn-md btn-danger">Cancel</a>
            </form>
        </div>
    </div>
</div>


{% endblock content %}

static_pages/templates/static_pages/home.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron jumbotron-fluid text-center">
    <div class="container">
      <h1 class="display-4">Welcome To My Blog</h1>
      <p class="lead">Django Blog</p>
    </div>
  </div>
{% endblock content %}